### ISSUE TITLE
Move changelog.txt to GitHub releases 

### ISSUE THREAD

**Issue by S-B99** [FINZ0/Osiris#27]
I'll do it myself if it isn't done when I get home.

**Comment by FINZ0** [comment]
changelog.txt is mainly just for me to write down changes but yeah it needs a readme

**Comment by S-B99** [comment]
You can put those changes in proper releases tho. And good on you for open sourcing this <3

**Comment by S-B99** [comment]
Readme bit is a duplicate of #25, just realised
