### ISSUE TITLE
Suggestions for fonzi

### ISSUE THREAD

**Issue by Novola** [FINZ0/Osiris#28]
- AutoWither (auto makes a line of like 10 withers and places the skulls hella fast)
- Black versions of the cape for OG osiris users
- AutoWeb
- totem pop counter
- FightAnnouncer and make it customisable (Basically what I mean by FightAnnouncer is it’d say in chat (name) just drunk a strength potion, or (name) just popped a totem! (name) just used weakness! etc)
- Enemy (Basically a command that lets you do -enemy add x and it'd target them more in a fight then others.
- AntiTrap (someway to make sure you don't get trapped idk zb0b said something about it
- RangeGreet (customisable) (says something like, You just entered my range! Have fun! whenever someone enters visual range)
- HotbarReplenish (save a preset of a hotbar, then when it gets low it replenishes it)
- ChatBot (You can add commands to it ingame like: !didyouknow and then you could set it up so when someone says that in chat, it'd respond with something else, etc etc, adding games to the bot aswell and some other shit.)
- TPABot (feature that allows you to add people to accept a tpa from in game and it'd do it)

**Comment by FINZ0** [comment]
Fucking put them in separate issues 4head
